apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywp1
    app.kubernetes.io/managed-by: Helm
  name: mywp1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myd
  type: NodePort
status:
  loadBalancer: {}

