apiVersion: v1
kind: Pod
metadata:
  name: podaffinity
spec:
   containers:
   - name: nginx-container
     image: nginx 
   affinity:
     nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - test
                - stag
