apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod3
spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  - key: app
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"
